### ISSUE TITLE
SeqIO.index_db problem

### ISSUE THREAD

**Issue by lilinzhou** [Jianwei-Zhang/DEGAP#1]
Hi, when I run ctglinker, I got the error below, it seems there are some problem with the index_db. I used the latest biopython (1.8.0)
can you help me to figure it out?
BUILD RAWREADS DICT
Traceback (most recent call last):
  File "/path/to/DEGAP/DEGAP.py", line 123, in <module>
    readsdict=SeqIO.index_db(out+"/reads.idx",reads,"fasta")
  File "/path/to/Python-3.9.6/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 999, in index_db
    return _SQLiteManySeqFilesDict(
  File "/path/to/Python-3.9.6/lib/python3.9/site-packages/Bio/File.py", line 323, in __init__
    self._load_index()
  File "/path/to/Python-3.9.6/lib/python3.9/site-packages/Bio/File.py", line 339, in _load_index
    (count,) = con.execute(
TypeError: cannot unpack non-iterable NoneType object

**Comment by HuangYicheng-Bio** [comment]
> Hi, when I run ctglinker, I got the error below, it seems there are some problem with the index_db. I used the latest biopython (1.8.0) can you help me to figure it out? BUILD RAWREADS DICT Traceback (most recent call last): File "/path/to/DEGAP/DEGAP.py", line 123, in readsdict=SeqIO.index_db(out+"/reads.idx",reads,"fasta") File "/path/to/Python-3.9.6/lib/python3.9/site-packages/Bio/SeqIO/**init**.py", line 999, in index_db return _SQLiteManySeqFilesDict( File "/path/to/Python-3.9.6/lib/python3.9/site-packages/Bio/File.py", line 323, in **init** self._load_index() File "/path/to/Python-3.9.6/lib/python3.9/site-packages/Bio/File.py", line 339, in _load_index (count,) = con.execute( TypeError: cannot unpack non-iterable NoneType object

Hi,

This issue arises from an incomplete indexing process. Possible reasons include: 1) Insufficient memory preventing the creation of reads.idx, and 2) If the process is run multiple times, the previous attempt may not have successfully created the reads.idx index, leading to errors when the second run skips the indexing step.

To resolve this, check your memory availability and delete the existing reads.idx index file from the output directory before re-running the process.

Best,
Yicheng
