### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by zsdxgl** [Jianwei-Zhang/DEGAP#4]
Thanks for the excellent program.
The log shows a error. How to deal with it? Thanks.

BUILD RAWREADS DICT
BUILD DICT SUCCEED
38859
48858.99999999999
Traceback (most recent call last):
  File "/data1/guoliang/HJS/4.gapclose/./DEGAP/DEGAP.py", line 158, in <module>
    selectedReads=selectRawReads(parameter,seedlen)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "workdir/DEGAP/selectRawReads.py", line 21, in __init__
    self.mode,self.remove,self.thread,self.reads,self.out,self.seqLeft,self.seqRight,self.flag,self.edge,self.filterDepth,self.MaximunExtensionLength,self.readsDict=parameterlist
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 12, got 10)

**Comment by zsdxgl** [comment]
The same error. Any suggestion?

**Comment by zsdxgl** [comment]
any suggestion?

**Comment by HuangYicheng-Bio** [comment]
> Thanks for the excellent program. The log shows a error. How to deal with it? Thanks.
> 
> BUILD RAWREADS DICT BUILD DICT SUCCEED 38859 48858.99999999999 Traceback (most recent call last): File "/data1/guoliang/HJS/4.gapclose/./DEGAP/DEGAP.py", line 158, in selectedReads=selectRawReads(parameter,seedlen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "workdir/DEGAP/selectRawReads.py", line 21, in **init** self.mode,self.remove,self.thread,self.reads,self.out,self.seqLeft,self.seqRight,self.flag,self.edge,self.filterDepth,self.MaximunExtensionLength,self.readsDict=parameterlist ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: not enough values to unpack (expected 12, got 10)

Could you provide more details about the command line you used to run Degap?

**Comment by zsdxgl** [comment]
Sorry for the delay. The command is below.

python ./DEGAP/DEGAP.py -t 10  --mode ctglinker --ctgseq ###.p_ctg.fa --reads hifi.fasta --remove 1 --out Output 

The contigs is assembled with hifiasm, the hifi.fasta is about 50X and the same reads used for hifiasm.

Thanks for the great job.

**Comment by xtbggqy** [comment]
Hello! I've encountered the same problem too. May I ask if you've solved it?

**Comment by HuangYicheng-Bio** [comment]
> Sorry for the delay. The command is below.
> 
> python ./DEGAP/DEGAP.py -t 10 --mode ctglinker --ctgseq ###.p_ctg.fa --reads hifi.fasta --remove 1 --out Output
> 
> The contigs is assembled with hifiasm, the hifi.fasta is about 50X and the same reads used for hifiasm.
> 
> Thanks for the great job.

Try "python ./DEGAP/DEGAP.py -t 10 --mode ctglinker --ctgseq ###.p_ctg.fa --reads hifi.fasta --out Output" 
This Bug will fixed soon.

**Comment by HuangYicheng-Bio** [comment]
> Sorry for the delay. The command is below.
> 
> python ./DEGAP/DEGAP.py -t 10 --mode ctglinker --ctgseq ###.p_ctg.fa --reads hifi.fasta --remove 1 --out Output
> 
> The contigs is assembled with hifiasm, the hifi.fasta is about 50X and the same reads used for hifiasm.
> 
> Thanks for the great job.

Try running: "python ./DEGAP/DEGAP.py -t 10 --mode ctglinker --ctgseq ###.p_ctg.fa --reads hifi.fasta --out Output"
This issue will be resolved soon.

**Comment by HuangYicheng-Bio** [comment]
> --remove 1



> Sorry for the delay. The command is below.
> 
> python ./DEGAP/DEGAP.py -t 10 --mode ctglinker --ctgseq ###.p_ctg.fa --reads hifi.fasta --remove 1 --out Output
> 
> The contigs is assembled with hifiasm, the hifi.fasta is about 50X and the same reads used for hifiasm.
> 
> Thanks for the great job.

I have run and tested your command, and the program runs smoothly without encountering the error you mentioned. 

Try running: "python ./DEGAP/DEGAP.py -t 10 --mode ctglinker --ctgseq ###.p_ctg.fa --reads hifi.fasta --out Output" and check whether the longest sequence in the ###.p_ctg.fa file is too short (shorter than the length of the longest reads)? Also, please verify if the Genome.inputCtg.fa file is being generated in the output folder.

**Comment by Yahagi-yz** [comment]
I also encountered the same issue. In fact, there are 10 parameters passed in the ctglinker mode, but in the selectRawReads.py script, the value is judged as 9, leading to passing it to another mode. You just need to modify the judgment in the script, changing 9 to 10. Here is an example of the modified code:


```

if len(parameterlist) == 10: #此处由9修改为10

    self.mode, self.remove, self.thread, self.reads, self.out, self.genomeSeq, self.edge, self.filterDepth, self.MaximunExtensionLength, self.readsDict = parameterlist

self.inputSeq = self.genomeSeq

    self.inputSeqDict = {}

    for gseq in SeqIO.parse(self.inputSeq, 'fasta'):

        self.inputSeqDict[gseq.id] = len(gseq.seq)

else:

    self.mode, self.remove, self.thread, self.reads, self.out, self.seqLeft, self.seqRight, self.flag, self.edge, self.filterDepth, self.MaximunExtensionLength, self.readsDict = parameterlist

```

**Comment by Jianwei-Zhang** [comment]
Please try our DEGAP v2.
